global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'windows_exporter'
    static_configs:
      - targets: ['localhost:9182']
        labels:
          instance: 'server'
          group: 'windows'

  - job_name: 'sql_exporter'
    static_configs:
      - targets: ['localhost:9237']
        labels:
          instance: 'server-sql'
          group: 'sql'

rule_files:
  - "rules.yml"